Removed some duplication from Agent, using the mapType as a class attribute, and some cleaning up (unless that was the last commit... I forget).
Something is broken in taxi.py when running the graph simulation, after the
preparation steps are finished.  It shouldn't be too hard to track down, but
this is NOT a working commit!

  File "C:\Source\hg\unified\agents\taxi.py", line 219, in compete
    (now(), self.name, targetFare.name, drive_dist))
TypeError: int argument required